# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter the main title of the banner.', max_length=500, null=True, verbose_name='Banner Title')),
                ('sub_title', models.CharField(blank=True, help_text='Enter the subtitle of the banner.', max_length=500, null=True, verbose_name='Banner Sub-Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter a brief description about the banner.', null=True, verbose_name='Banner Description')),
                ('see_more_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter a brief see more description.', null=True, verbose_name='See More Description')),
                ('our_channel_url', models.URLField(blank=True, help_text='Provide the link to your our channel url (optional).', max_length=500, null=True, verbose_name='Our Channel Url')),
                ('video', models.FileField(blank=True, help_text='Upload a promotional video (MP4, AVI, etc).', null=True, upload_to='banners/videos/', verbose_name='Banner Video')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image representing the team or a team member.', null=True, upload_to='homepage/temas/', verbose_name='Team Image')),
                ('title', models.CharField(blank=True, help_text='Enter the title or name of the team or member.', max_length=500, null=True, verbose_name='Team Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Provide a brief description of the team or member.', null=True, verbose_name='Team Description')),
                ('url', models.URLField(blank=True, help_text='Provide a relevant link, such as a LinkedIn or portfolio URL.', max_length=500, null=True, verbose_name='Team Profile URL')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your whychooseus image...', null=True, upload_to='homepage/why-choose-us/', verbose_name='WhyChooseUs Image')),
                ('sub_image', models.ImageField(blank=True, help_text='Upload your whychooseus-sub image...', null=True, upload_to='homepage/why-choose-us/', verbose_name='WhyChooseUs Sub-Image')),
                ('title', models.CharField(blank=True, help_text='Enter your whychooseus title...', max_length=500, null=True, verbose_name='WhyChooseUs Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter your whychooseus description...', null=True, verbose_name='WhyChooseUs description')),
            ],
            options={
                'verbose_name': 'Why Choose Us',
                'verbose_name_plural': 'Why Choose Us',
                'ordering': ['-id'],
            },
        ),
    ]
