# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=500, verbose_name='Price')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Subscription Content')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['id'],
            },
        ),
    ]
