# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload image.', null=True, upload_to='', verbose_name='Image')),
                ('video', models.FileField(blank=True, help_text='Upload video.', null=True, upload_to='', verbose_name='Video')),
                ('title', models.CharField(blank=True, help_text='Enter the section title.', max_length=500, null=True, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter the full content.', null=True, verbose_name='Body')),
                ('menu', models.ForeignKey(help_text='Select the header menu this content belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='header_menus', to='configuration.headermenu', verbose_name='Header Menu')),
            ],
            options={
                'verbose_name': 'Page Header Content',
                'verbose_name_plural': 'Page Header Contents',
                'ordering': ['-id'],
            },
        ),
    ]
