# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image representing the service (e.g. icon or illustration).', null=True, upload_to='services/', verbose_name='Service Image')),
                ('title', models.CharField(blank=True, help_text='Enter the name or title of the service.', max_length=500, null=True, verbose_name='Service Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Provide a brief description of the service offered.', null=True, verbose_name='Service Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-id'],
            },
        ),
    ]
