# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Upload a video file (e.g., MP4, AVI) for this channel.', null=True, upload_to='channels/videos/', verbose_name='Channel Video')),
                ('title', models.CharField(blank=True, help_text='Enter the title or name of the channel.', max_length=500, null=True, verbose_name='Channel Title')),
                ('insta_broadcast', models.URLField(blank=True, help_text='Enter the broadcast URL for Instagram.', max_length=500, null=True, verbose_name='Instagram Broadcast URL')),
                ('fb_broadcast', models.URLField(blank=True, help_text='Enter the broadcast URL for Facebook.', max_length=500, null=True, verbose_name='Facebook Broadcast URL')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Write a brief description of this channel.', null=True, verbose_name='Channel Description')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-id'],
            },
        ),
    ]
