# Generated by Django 5.2.4 on 2025-07-25 22:08

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crypto Course',
                'verbose_name_plural': 'Crypto Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-commerce Course',
                'verbose_name_plural': 'E-commerce Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceSingleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Course Image')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('video', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('advance', 'Advance'), ('basic', 'Basic')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education Video',
                'verbose_name_plural': 'Education Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Updates Course',
                'verbose_name_plural': 'Market Updates Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Trades Course',
                'verbose_name_plural': 'Stock Trades Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SingleCourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=180, verbose_name='Course Bundle Name')),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(default=0)),
                ('final_price', models.PositiveIntegerField(editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_course_bundles', to='crouses.ecommercesinglecourse')),
            ],
        ),
    ]
